-- Drop existing function if it exists
drop function if exists create_pdf_documents_table();

-- Drop existing table if it exists
drop table if exists pdf_documents;

-- Create the pdf_documents table
create table pdf_documents (
  id bigint generated by default as identity primary key,
  title text not null,
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Add full text search capabilities
alter table pdf_documents add column content_vector tsvector
  generated always as (to_tsvector('english', content)) stored;

create index pdf_documents_content_vector_idx
  on pdf_documents using gin(content_vector); 