-- Function to create the pdf_documents table
create or replace function create_pdf_table()
returns void
language plpgsql
security definer
as $$
begin
  -- Create the table if it doesn't exist
  create table if not exists pdf_documents (
    id bigint generated by default as identity primary key,
    title text not null,
    content text not null,
    content_vector tsvector,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
  );

  -- Create the GIN index if it doesn't exist
  if not exists (
    select 1
    from pg_indexes
    where tablename = 'pdf_documents'
    and indexname = 'pdf_documents_content_vector_idx'
  ) then
    create index pdf_documents_content_vector_idx on pdf_documents using gin(content_vector);
  end if;
end;
$$;

-- Function to update content vectors
create or replace function update_content_vectors()
returns void
language plpgsql
security definer
as $$
begin
  -- Update content vectors for all documents
  update pdf_documents
  set content_vector = to_tsvector('english', content)
  where content_vector is null;
end;
$$; 